###
GET http://192.168.1.16:3000/oferecer


###
POST http://192.168.1.16:3000/solicitar
Content-Type: application/json

{
    "matricula": 111111,
    "nomeDestino": "Seara",
    "nomePartida": "Bloco 910",
    "latitudeDestino":123,
    "longitudeDestino":456,
    "latitudePartida":789,
    "longitudePartida":101112
}


###
GET http://192.168.1.7:3000/carros/1


###
POST http://192.168.1.16:3000/create
Content-Type: application/json

{
    "userName": "teste",
    "userEmail": "teste@teste.com",
    "userMatricula": "2",
    "userPassword": "2"
}

###
POST http://192.168.1.16:3000/login
Content-Type: application/json

{
    "userMatricula": "12345",
    "userPassword": "password"
}

###
POST http://192.168.1.16:3000/login
Content-Type: application/json

{
    "userMatricula": "1111",
    "userPassword": "password"
}

###
GET http://192.168.1.16:3000/username/12345

###
GET http://192.168.1.16:3000/data/101010


###
POST http://192.168.1.16:3000/update
Content-Type: application/json

{
    "matricula": "1",
    "emailVisibility": false
}