POST http://192.168.1.16:3000/create
Content-Type: application/json

{
    "userName": "caio",
    "userEmail": "caio@teste.com",
    "userMatricula": "12345",
    "passwordUser": "password"
}

###
POST http://192.168.1.16:3000/login
Content-Type: application/json

{
    "userMatricula": "12345",
    "userPassword": "password"
}

###
POST http://192.168.1.16:3000/login
Content-Type: application/json

{
    "userMatricula": "1111",
    "userPassword": "password"
}
