POST http://localhost:4002/products
Content-Type: application/json

{
    "name": "Caneta Li",
    "price": 3
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/c95023fb-23c6-4a28-8356-2f0b80e72416